### ISSUE TITLE
Possibility to change default provider (website)?

### ISSUE THREAD

**Issue by matdam99** [anfreire/updateMe-Mobile#31] opened 2024-08-24 03:23 UTC
Hello, 

In the next version of the app, would it be possible to change the default website from Modyolo to Liteapks? Is there any way to give the user choice to choose their preference?

Also, is it possible to assign a specific website to a specific app to pull future updates from? For instance, there is always a star next to Modyolo. I would like to change the preference of the source website (provider) on a per-app basis. Can this be done? 

Regards,
Mat

**Comment by Felitendo** [comment] 2024-08-28 08:38
Duplicate of #24

**Comment by anfreire** [comment] 2024-09-08 10:18
Thank you, @Felitendo 

Closing this issue as duplicated. The follow-up process will be available in the issue #24

**Closed by anfreire** 2024-09-08 10:18 UTC
