### ISSUE TITLE
Add ability to ignore updates per app.

### ISSUE THREAD

**Issue by DoYouKnowMyNamePlz** [anfreire/updateMe-Mobile#17] opened 2024-08-06 20:12 UTC
As the title says, add a way to ignore updates for certain apps. Say I already own one of these apps just for an example we'll say SDMaidSE, it would be nice to have the ability to disable update checks for that app.

Possibly of holding down on the app in question has a context menu pop up to disable it?

**Comment by anfreire** [comment] 2024-08-06 20:58
Closing this as a duplicate of #8

**Closed by anfreire** 2024-08-06 20:58 UTC
Labels: duplicate
